version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      FLASK_ENV: developement
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/user/src/app
    depends_on:
      - backend

  db:
    image: mongo
    volumes:
      - ./data:/data/db
